app = 'wallet-money-api-gateway'
primary_region = 'ams'
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 80
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 200
    soft_limit = 180
    type = "connections"

[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "5s"
    restart_limit = 0
    timeout = "2s"

  [[tls]]
    cert_file = "/etc/letsencrypt/live/wallet-money-api-gateway.fly.dev/fullchain.pem"
    key_file = "/etc/letsencrypt/live/wallet-money-api-gateway.fly.dev/privkey.pem"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
